version: "3"
services:
  ec2:
    build: ./amazonlinux
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/php-fpm/www.conf:/etc/php-fpm.d/www.conf
      - ../src/code:/srv/
    ports:
      - "80:80"
    depends_on:
      - mariadb
    privileged: true
  mariadb:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: frontier
    volumes:
        - ./data/mariadb:/var/lib/mysql
    ports:
        - "3306:3306"
